version: '3'

services:
  backend:
    build: ./server
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - ./server:/back/app
  frontend:
    build: ./client/store
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/front/app
    links:
      - "backend"