version: '3'

services:
  backend:
    build: 
          context: ./server
          dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/app
  frontend:
    build:
          context: ./client/store
          dockerfile: Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/app
    links:
      - "backend"